networks:
  gmao-network:

volumes:
  pgdata:

services:
  db:
    image: postgres:15-alpine
    container_name: gmao-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gmao-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: D@n@kil31989
        POSTGRES_DB: gmao
    env_file:
      - ./back/.env
    container_name: gmao-backend    
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D@n@kil31989
      POSTGRES_DB: gmao       
    expose:         # 👈 important : uniquement exposé au réseau interne Docker
      - "3000"
    depends_on:
      - db
    networks:
      - gmao-network

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      args:
        VITE_API_URL: "/api"   # 👈 proxy via nginx
    container_name: gmao-frontend
    # environment:
    #   - REACT_APP_API_URL=/api
    ports:         # 👈 pas besoin de le mapper sur le host
      - "80:80"
    depends_on:
      - backend
    networks:
      - gmao-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: gmao-nginx
  #   ports:
  #     - "80:80"   # 👈 SEUL nginx expose sur le host
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - gmao-network
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
