BEGIN;

DROP TABLE IF EXISTS "user", "service", "role", "intervention", "documentation", "parent","movement", "material", "preventive", "status", "priority", "localisation", "category", "type", "material_preventive", "material_intervention", "user_intervention", "status_intervention";

CREATE TABLE "status" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE TABLE "priority" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "localisation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "category" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "service" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "role" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "parent"(
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"label" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "user" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"lastname" VARCHAR(255) NOT NULL,
	"firstname" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"user_role" INTEGER NOT NULL REFERENCES "role"("id") ,
	"user_service" INTEGER  NOT NULL REFERENCES "service"("id"),
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE TABLE "intervention" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255),
	"description" TEXT,
	"detail" VARCHAR(255),	
	"initial_comment" VARCHAR(255),
	"final_comment" VARCHAR(255),
	"begin_date" TIMESTAMPTZ,	
	"picture" BYTEA,
	"mimetype" VARCHAR(255),
	"service_intervention" INTEGER REFERENCES "service"("id"),
	"localisation_label" INTEGER REFERENCES "localisation"("id"),
	"status_label" INTEGER REFERENCES "status"("id"),
	"category_label" INTEGER REFERENCES "category"("id"),
	"priority_label" INTEGER REFERENCES "priority"("id"),
	"type_label" INTEGER REFERENCES "type"("id"),	
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE TABLE "material" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"is_store" BOOLEAN NOT NULL DEFAULT false,
	"name" VARCHAR(255) NOT NULL,
	"brand" VARCHAR(255),
	"model" VARCHAR(255),
	"description" TEXT,
	"quantity" INTEGER,	
	"registration" VARCHAR(255),
	"serial_number" VARCHAR(255),
	"engine_number" VARCHAR(255),
	"buy_date" TIMESTAMPTZ,
	"comment" TEXT,
	"picture" BYTEA,
	"mimetype" VARCHAR(255) NOT NULL,
	"service_material" INTEGER REFERENCES "service"("id"),
	"category_material" INTEGER REFERENCES "category"("id"),
	"status_material" INTEGER REFERENCES "status"("id"),
	"localisation_material" INTEGER REFERENCES "localisation"("id"),	
	"parent_material" INTEGER REFERENCES "parent"("id"),	
	"type_material" INTEGER REFERENCES "type"("id"),				
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id")
);

CREATE TABLE "documentation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"file" BYTEA,
	"mimetype" VARCHAR(255) NOT NULL,
	"material_concerned" INTEGER REFERENCES "material"("id"),
	PRIMARY KEY("id")		
);

CREATE TABLE "movement"(
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"is_incoming" BOOLEAN NOT NULL DEFAULT false,
	"is_outgoing" BOOLEAN NOT NULL DEFAULT false,
	"material_concerned" INTEGER REFERENCES "material"("id"),
	PRIMARY KEY("id")
);


CREATE TABLE "preventive" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255),
	"description" TEXT,
	"process" TEXT,	
	"date" TIMESTAMPTZ,
	"service_preventive" INTEGER REFERENCES "service"("id"),
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id")
);


-- Liaison many to many matériel et préventif
CREATE TABLE "material_preventive" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"material_id" INTEGER NOT NULL REFERENCES "material"("id"),
	"preventive_id" INTEGER NOT NULL REFERENCES "preventive"("id"),
	PRIMARY KEY("id")
);

-- Liaison many to many matériel et intervention
CREATE TABLE "material_intervention" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"material_id" INTEGER NOT NULL  REFERENCES "material"("id"),
	"intervention_id" INTEGER NOT NULL  REFERENCES "intervention"("id"),
	PRIMARY KEY("id")
);

-- -- Liaison many to many status et intervention
 CREATE TABLE "status_intervention" (
 	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
 	"status_id" INTEGER NOT NULL  REFERENCES "status"("id"),
 	"intervention_id" INTEGER NOT NULL  REFERENCES "intervention"("id"),
	"comment" TEXT,
	"date" TIMESTAMPTZ DEFAULT NOW(),
 	PRIMARY KEY("id")
 );

-- Liaison many to many user et intervention
 CREATE TABLE "user_intervention" (
 	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
 	"intervention_id" INTEGER NOT NULL  REFERENCES "intervention"("id"),
 	"user_id" INTEGER NOT NULL  REFERENCES "user"("id"),
 	PRIMARY KEY("id")
 );


COMMIT;